[package]
name = "phi-recorder-native"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
license = "GPL-3.0-or-later"

[lib]
name = "phi_recorder"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.28"
phi-recorder-core = { path = "renderer-core" }
phi-recorder-protocol = { path = "renderer-protocol" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.138"

[dev-dependencies]
tempfile = "3"

[workspace]
resolver = "2"
members = ["renderer-protocol", "renderer-host"]

[patch."https://github.com/2278535805/miniquad"]
miniquad = { git = "https://github.com/NuanRMxi-Lazy-Team/miniquad", rev = "b3aaa47a3c42cd99e64ec8a96b325cdd799fd2dc" }

[profile.release]
lto = "thin"
strip = true
opt-level = 3
