use crate::abi::{
    phi_render_config_t, phi_string_view, phi_string_view_t, PHI_ABI_VERSION,
    PHI_AUDIO_MIX_MODE_OPTIMIZED, PHI_CHALLENGE_COLOR_RAINBOW,
};

impl phi_render_config_t {
    pub(crate) fn defaults() -> Self {
        Self {
            struct_size: std::mem::size_of::<Self>() as u32,
            abi_version: PHI_ABI_VERSION,
            resolution: crate::phi_resolution_t {
                width: 1920,
                height: 1080,
            },
            ending_length: 0.0,
            render_loading: 0,
            hires: 0,
            chart_debug_line: 0.0,
            chart_debug_note: 0.0,
            chart_ratio: 1.0,
            all_good: 0,
            all_bad: 0,
            fps: 60,
            hardware_accel: 1,
            hevc: 0,
            mpeg4: 0,
            custom_encoder: phi_string_view_t::empty(),
            dynamic_bitrate_control: 1,
            bitrate: phi_string_view("28"),
            aggressive_chart: 1,
            aggressive_note: 0,
            aggressive_particle: 0,
            challenge_color: PHI_CHALLENGE_COLOR_RAINBOW,
            challenge_rank: 3,
            note_scale: 1.0,
            particle: 1,
            player_avatar: phi_string_view_t::empty(),
            player_name: phi_string_view("HLMC"),
            player_rks: 16.0,
            sample_count: 8,
            fxaa: 0,
            resource_pack_path: phi_string_view_t::empty(),
            speed: 1.0,
            volume_music: 0.5,
            volume_sfx: 0.4,
            force_limit: 1,
            limit_threshold: 0.5,
            loudness_equalization: 0,
            audio_mix_mode: PHI_AUDIO_MIX_MODE_OPTIMIZED,
            watermark: phi_string_view_t::empty(),
            roman: 0,
            chinese: 0,
            combo: phi_string_view("AUTOPLAY"),
            difficulty: phi_string_view_t::empty(),
            judge_offset: 0.0,
            file_name_format: phi_string_view("%date% %time% %info.name%_%level_prefix%"),
            render_line: 1,
            render_line_extra: 1,
            render_note: 1,
            render_double_hint: 1,
            render_ui_pause: 1,
            render_ui_name: 1,
            render_ui_level: 1,
            render_ui_score: 1,
            render_ui_combo: 1,
            render_ui_bar: 1,
            render_bg: 1,
            render_bg_dim: 1,
            preserve_framebuffer: 0,
            render_extra: 1,
            background_blurriness: 80.0,
            max_particles: 5000,
            play_start_time: 0.0,
            play_end_time: 0.0,
            has_play_end_time: 0,
            fade: 0.0,
            alpha_tint: 0,
        }
    }
}
